-- Add import-inference signal types to the SignalType enum.
-- PostgreSQL ALTER TYPE ... ADD VALUE is non-destructive and irreversible,
-- so IF NOT EXISTS guards are used to make this idempotent.

ALTER TYPE "SignalType" ADD VALUE IF NOT EXISTS 'IMPORT_HIGH_INTENT';
ALTER TYPE "SignalType" ADD VALUE IF NOT EXISTS 'IMPORT_MEDIUM_INTENT';
ALTER TYPE "SignalType" ADD VALUE IF NOT EXISTS 'IMPORT_LOW_INTENT';
ALTER TYPE "SignalType" ADD VALUE IF NOT EXISTS 'IMPORT_RECENT_CONTACT';
ALTER TYPE "SignalType" ADD VALUE IF NOT EXISTS 'IMPORT_WARM_CONTACT';
ALTER TYPE "SignalType" ADD VALUE IF NOT EXISTS 'IMPORT_STALE_CONTACT';
ALTER TYPE "SignalType" ADD VALUE IF NOT EXISTS 'IMPORT_ACTIVE_INTEREST';
ALTER TYPE "SignalType" ADD VALUE IF NOT EXISTS 'IMPORT_NEGATIVE_SIGNAL';
