// This file will be auto-generated by `npx supabase gen types typescript`
// after the database schema is applied in Phase 1.
// For now it provides the type placeholder so Supabase clients compile.

export type Database = {
  public: {
    Tables: Record<string, unknown>
    Views: Record<string, unknown>
    Functions: Record<string, unknown>
    Enums: Record<string, unknown>
  }
}
