/**
 * Leadkaun's own invoice identity — the "from" block, contact details, and tax
 * treatment printed on every customer-facing invoice PDF.
 *
 * This is the ONE place to edit invoice legal details. Razorpay's own invoice is
 * still recorded against each payment (Invoice.provider_ref) for audit, but the
 * document customers download is generated by us from the fields below.
 *
 * TODO (before real invoices go out): fill `addressLines` with the registered
 * business address. When Leadkaun registers for GST, flip `gst.registered` to
 * true and set `gstin` + `stateCode` — the PDF then becomes a "Tax Invoice"
 * with an 18% CGST/SGST (or IGST) breakup automatically.
 */
export const INVOICE_ISSUER = {
  brand: "Leadkaun",
  // Registered legal entity name. Keep as "Leadkaun" until a different
  // registered name applies — the product/billing identity is Leadkaun, never
  // the email domain.
  legalName: "Leadkaun",
  // Registered business address, one string per line. Leave empty to omit.
  addressLines: [] as string[],
  email: "hello@leadkaun.com",
  website: "leadkaun.com",
  gst: {
    registered: false,
    gstin: "", // e.g. "29ABCDE1234F1Z5"
    rate: 18, // %
    stateCode: "", // issuer's state, for CGST/SGST vs IGST place-of-supply
  },
  // Standard SAC for SaaS / IT services — only shown when GST is enabled.
  sac: "998314",
  // Prefix for the consecutive invoice serial (e.g. LK-00001).
  numberPrefix: "LK",
} as const
